default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.4.0'
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--check"]
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements/prod.txt"]
        verbose: true
      - id: poetry-export
        args: ["--with", "dev", "-f", "requirements.txt", "-o", "requirements/dev.txt"]
        verbose: true
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.253'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: '23.1.0'
    hooks:
      - id: black
