# Generated by Django 4.1.2 on 2023-06-10 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="designation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="designation_employee",
                to="employee.designation",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_employee",
                to="employee.team",
            ),
        ),
    ]
